# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install -y pandoc pybind11-dev gfortran
        sudo apt-get install -y --no-install-recommends software-properties-common
        sudo add-apt-repository ppa:fenics-packages/fenics
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends fenics

        pip3 install --upgrade pip
        pip3 install pytest
        pip3 install -r requirements.txt
        pip3 install git+https://github.com/BAMresearch/fenics_helpers
        pip3 install --user -e .
    - name: Run
      run: |
        export PATH=/home/runner/.local/bin/:$PATH
        doit
        pytest
    - name: deploy
      if: github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@4.0.0-beta-01
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: website # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy branch
